---
root: true
extends:
  - react-app
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  impliedStrict: true
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  no-mixed-spaces-and-tabs: error
  '@typescript-eslint/semi': [error, always]
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  prefer-const: error
  semi: off
  eol-last: [error, always]

  # https://eslint.org/docs/rules/#possible-errors
  for-direction: error
  getter-return: error
  no-cond-assign: error
  no-empty: error
  # disabled, because leads to false positive parenthesized body of function
  # no-extra-parens: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-sparse-arrays: error
  no-unexpected-multiline: warn # check with 'semi' rule
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-typeof: error
  space-in-parens: ['error', 'never']

  # https://eslint.org/docs/rules/#best-practices
  curly: error
  dot-location: [error, property]
  eqeqeq: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-else-return: [error, { allowElseIf: false }]
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-multi-spaces: error
  no-return-await: error

  # https://eslint.org/docs/rules/#stylistic-issues
  quote-props: [error, as-needed]
  object-curly-spacing: [error, always]
  comma-spacing: error
  comma-dangle: off
  no-multiple-empty-lines: [error, { max: 1 }]
  no-trailing-spaces: error
  keyword-spacing: error
  space-before-blocks: error
  arrow-spacing: [error, { before: true, after: true }]
  brace-style: [error, 1tbs]
